PDF_CHUNK_SIZE = 500
PDF_CHUNK_OVERLAP = 50
TOP_K = 2
TEMPERATURE = 0.3
LLM_MODEL = "qwen2.5:1.5b"
EMBEDDING_MODEL = "bge-m3"
CHROMA_PERSIST_DIRECTORY = "./chroma_db"
OLLAMA_BASE_URL = "http://localhost:11434"
