# -*- coding: utf-8 -*-
"""study2-1.ipynb

Automatically generated by Colab.
"""

# !pip install datasets
import spacy
from collections import Counter
from datasets import load_dataset

nlp = spacy.load("en_core_web_sm")
realnewslike = load_dataset("allenai/c4", "realnewslike", streaming=True, split="train")

word_freq = Counter()

print("Start")
for i, example in enumerate(realnewslike):
    doc = nlp(example["text"])
    words = [
        token.lemma_.lower()          # 見出し語化
        for token in doc
        if not token.is_stop           # ストップワード除去
        and not token.is_punct         # 句読点除去
        and not token.is_space         # 空白除去
        and token.is_alpha             # アルファベットのみ
    ]
    word_freq.update(words)

    if i >= 1000:
        break

print(word_freq.most_common(20))
